[package]
name = "rust_client"
version = "0.1.0"
authors = ["Yuri-M-Dias <yurimathe.yp@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0.64"

